spring:
  data:
    mongodb:
      uri: mongodb://admin:admin@scpi-invest-partner-db:27017/scpi-invest-partner-db?authSource=admin
  application:
    version: 1.0.0
    name: scpi-invest-plus-partner
  kafka:
    bootstrap-servers: kafka-svc.kafka:9094

notification-service-url: http://notification-service.scpi-invest-plus-int:8080