apiVersion: v1
kind: Service
metadata:
  name: scpi-invest-partner-db
spec:
  selector:
    app: scpi-invest-partner-db
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: ClusterIP