apiVersion: apps/v1
kind: Deployment
metadata:
  name: partner-service
  labels:
    app: partner-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: partner-service
  template:
    metadata:
      name: partner-service
      labels:
        app: partner-service
    spec:
      containers:
        - name: partner-service
          image: "{{.Values.image.repo}}/{{.Values.image.name}}:{{.Values.image.tag}}"
          imagePullPolicy: Always
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "{{.Values.application.environment }}"
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
      