apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mongo-express-tls
spec:
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: lets-encrypt
  secretName: mongo-express-tls
  dnsNames:
    - {{ if .Values.ingressMongoExpressPrefix }}{{ .Values.ingressMongoExpressPrefix }}.{{ end }}mongo-express.check-consulting.net
  usages:
    - digital signature
    - key encipherment